name: Checkout
on: [push, pull_request]
jobs:
    test:
        name: unit tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                ref: ['master', 'v6.9.0']
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '12'
            - uses: ./checkout
              with:
                  ref: ${{ matrix.ref }}
            - run: jhipster --version
            - run: ls ${{ github.workspace }}/../
